server-port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/player_service
    username: root
    password:
  #jpa:
  #  hibernate.ddl.auto: update

  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml