server.port: 8085

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: Betting_Transfer_Group_Id
      properties:
        spring:
          json:
            trusted:
              packages: 'org.example.LeoProjectKafkaDTOS'

  liquibase:
    change-log: classpath:/liquibase/changelog-master.xml

  datasource:
    url: jdbc:mysql://localhost:3306/player_service
    username: root
    password: password


